# Generated by Django 3.0.6 on 2020-05-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=208, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
