# Generated by Django 3.0.6 on 2020-05-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0002_auto_20200514_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='pdf',
            new_name='year12',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='date',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='date',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='year',
        ),
        migrations.AddField(
            model_name='subject',
            name='year13',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='year14',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='year15',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='year16',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='year17',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='year18',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
