# Generated by Django 3.0.6 on 2020-05-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0003_auto_20200518_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subjects',
            field=models.CharField(max_length=208, null=True),
        ),
    ]
