# Generated by Django 3.0.6 on 2020-05-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0004_subject_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year12', models.FileField(blank=True, upload_to='')),
                ('year13', models.FileField(blank=True, upload_to='')),
                ('year14', models.FileField(blank=True, upload_to='')),
                ('year15', models.FileField(blank=True, upload_to='')),
                ('year16', models.FileField(blank=True, upload_to='')),
                ('year17', models.FileField(blank=True, upload_to='')),
                ('year18', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year12',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year13',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year14',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year15',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year16',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year17',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='year18',
        ),
    ]
