# Generated by Django 3.0.6 on 2020-05-18 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0005_auto_20200518_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='btech.Subject'),
        ),
    ]
