# Generated by Django 3.0.6 on 2020-05-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0007_auto_20200518_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Steam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='btech.Upload'),
        ),
    ]
