# Generated by Django 3.0.6 on 2020-05-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0009_auto_20200518_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
