# Generated by Django 3.0.6 on 2020-05-22 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0011_auto_20200522_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='btech.Subject'),
        ),
    ]
