# Generated by Django 3.0.6 on 2020-05-22 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0012_semester_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='steams',
        ),
        migrations.RemoveField(
            model_name='year',
            name='sem',
        ),
        migrations.AddField(
            model_name='semester',
            name='steams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='btech.Upload'),
        ),
        migrations.AddField(
            model_name='subject',
            name='sem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='btech.Semester'),
        ),
        migrations.AddField(
            model_name='year',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='btech.Subject'),
        ),
    ]
