# Generated by Django 3.0.6 on 2020-05-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0013_auto_20200522_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjects',
            field=models.CharField(blank=True, default=None, max_length=208),
        ),
    ]
