# Generated by Django 3.0.6 on 2020-05-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0014_auto_20200522_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjects',
            field=models.CharField(default=None, max_length=208),
        ),
    ]
