# Generated by Django 3.0.6 on 2020-05-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0015_auto_20200522_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjects',
            field=models.CharField(blank=True, max_length=208),
        ),
    ]
