# Generated by Django 3.0.6 on 2020-05-22 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0017_auto_20200522_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='stream1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='btech.Upload'),
        ),
    ]
