# Generated by Django 3.0.6 on 2020-05-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0018_subject_stream1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='sem',
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
