# Generated by Django 3.0.6 on 2020-05-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0019_auto_20200522_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='stream1',
            new_name='stream',
        ),
    ]
