# Generated by Django 3.0.6 on 2020-05-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0021_auto_20200524_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], max_length=204, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='stream',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('CIVIL', 'Civil Engineering'), ('MECHANICAL', 'Mechanical Engineering'), ('ECE', 'Electrical and Communication Engineering'), ('EE', 'Electrical Engineering')], max_length=204, null=True),
        ),
    ]
