# Generated by Django 3.0.6 on 2020-05-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0022_auto_20200524_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='sub',
            field=models.CharField(max_length=208, null=True),
        ),
    ]
