# Generated by Django 3.0.6 on 2020-05-25 07:09

import btech.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0023_auto_20200525_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='sub',
            field=models.CharField(max_length=208, null=True, verbose_name=btech.models.Subject),
        ),
    ]
